name: Build WordPress Plugin Zip

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build wp-geneapp.zip
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create wp-geneapp plugin zip
        run: |
          mkdir wp-geneapp-package
          cp -r * wp-geneapp-package/
          rm -rf wp-geneapp-package/.git wp-geneapp-package/.github
          cd wp-geneapp-package
          zip -r ../wp-geneapp.zip wp-geneapp

      - name: Upload plugin zip to release
        uses: softprops/action-gh-release@v1
        with:
          files: wp-geneapp.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
