name: Build WordPress Plugin Zip

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build wp-geneapp.zip
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Package plugin into wp-geneapp.zip
        run: |
          mkdir package
          rsync -av --progress ./ ./package/wp-geneapp --exclude .git --exclude .github --exclude wp-geneapp.zip
          cd package
          zip -r ../wp-geneapp.zip wp-geneapp

      - name: Upload plugin zip to release
        uses: softprops/action-gh-release@v1
        with:
          files: wp-geneapp.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
